---
title: "Reading data from the web"
author: "Rae Spriggs"
date: "2022-10-13"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## NSDUH  

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

```{r}
table_marj = 
  drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)
```

## SW Data

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

How do I get the stuff I want? 
```{r}
sw_titles = 
  swm_html %>% 
  html_elements(".lister-item-header a") %>% 
  html_text()

sw_runtime = 
  swm_html %>% 
  html_elements(".runtime") %>% 
  html_text()

sw_money = 
  swm_html %>% 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

sw_df = 
  tibble(
    title = sw_titles, 
    runtime = sw_runtime, 
    money = sw_money
  )
```
 
 Now looking at Napoleon Dynamite 
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = 
  tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```
 
## APIs 

NYC OpenData water consumption data 
```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

```

 BRFSS data (WILDFIRE AND MENTAL HEALTH DATA - DISSERTATION RESEARCH)
 
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

Pokemon data 

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

names(poke)

poke$name

poke$abilities

poke[["stats"]]

```


